# Generated by Django 4.2.11 on 2024-04-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nome do Campus"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Campus Ativo"),
                ),
            ],
        ),
    ]
