# Generated by Django 4.2.11 on 2024-04-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aluno", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nome do Curso"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aluno.campus",
                        verbose_name="Campus do Curso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomeCompleto",
                    models.CharField(
                        max_length=255, verbose_name="Nome Completo do Aluno"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "cpf",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="CPF do Aluno"
                    ),
                ),
                (
                    "dataNascimento",
                    models.DateTimeField(verbose_name="Data de Nascimento do Aluno"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("1", "Vinculado"),
                            ("2", "Formado"),
                            ("3", "Jubilado"),
                            ("4", "Evadido"),
                        ],
                        default="VINCULADO",
                        max_length=50,
                        verbose_name="Situação do Aluno",
                    ),
                ),
                (
                    "formaIngresso",
                    models.CharField(
                        choices=[("1", "Vestibular"), ("2", "SISU"), ("3", "PSEnem")],
                        default="VESTIBULAR",
                        max_length=50,
                        verbose_name="Forma de Ingresso do Aluno",
                    ),
                ),
                (
                    "matricula",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Matrícula do Aluno",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="aluno_foto/"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aluno.curso",
                        verbose_name="Curso do Aluno",
                    ),
                ),
            ],
        ),
    ]
