# Generated by Django 4.2.11 on 2024-04-11 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aluno", "0002_alter_campus_ativo_curso_aluno"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campus",
            options={"verbose_name_plural": "Campi"},
        ),
    ]
